### ISSUE TITLE
[Feature Request] command to just return active version

### ISSUE THREAD

**Issue by josh-burton** [fluttertools/fvm#334]
## Before creating a feature request make sure the suggestion fit within our [principles](https://fvm.app/docs/getting_started/overview#principles)

**Is your feature request related to a problem? Please describe.**
I'm setting up FVM with Github actions and want to cache the Flutter SDK.

I'd rather not cache the entire FVM cache directory, but just the active Flutter SDK version. 

I can't seem to find an FVM command that will just return the active version, e.g. beta, dev etc.

**Describe the solution you'd like**
A parameter added to the list command which only prints the active version: 

`fvm list --active`
prints `beta`

**Describe alternatives you've considered**

**Additional context**

**Comment by leoafarias** [comment]
@josh-burton by the active version you mean the active version within a specific project? `fvm doctor` returns a lot of information about the current environment fvm is running in, maybe a flag `fvm doctor --active-release` might be a better option to just output the active release being used within the env.

Let me know what you think.

**Comment by kuhnroyal** [comment]
Hi @josh-burton, I experimented a lot with FMV in Github actions but found it the easiest to just use plain Flutter there.

I created a PR in subosito/flutter-action which allows to read FVM config files easily.
https://github.com/subosito/flutter-action/pull/103

Without this change I am using this:
```yaml
      - name: Determine Flutter version
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: '.fvm/fvm_config.json'
          prefix: fvm
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.fvm_flutterSdkVersion }}
```
